"""empty message

Revision ID: 5144b19defda
Revises: 
Create Date: 2023-06-24 22:03:29.153035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5144b19defda'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.alter_column('option_a',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('option_b',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('option_c',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.String(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.alter_column('option_c',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=1),
               existing_nullable=False)
        batch_op.alter_column('option_b',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=1),
               existing_nullable=False)
        batch_op.alter_column('option_a',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=1),
               existing_nullable=False)

    # ### end Alembic commands ###
